name = "Testmod"
modid = "testmod"
version = "${version}"

[[transforms]]
name = "test transform"
target = "net.minecraft.client.main.Main"
path = "felis.testmod.MainTransformation"

[[entrypoints]]
id = "loader_plugin"
path = "felis.testmod.TestLoaderPlugin"