schema = 1
name = "Testmod"
modid = "testmod"
version = "${version}"

[[transformations]]
name = "test transform"
targets = ["net.minecraft.client.main.Main"]
specifier = "io.github.testmod.MainTransformation"

[[entrypoints]]
id = "loader_plugin"
specifier = "io.github.testmod.TestLoaderPlugin"