name="Testmod"
version = "1.0.0"
description = "An API for the ModLoader project"
modid = "loader_api"

[[transforms]]
name = "bootstrap transformation for common entrypoint"
class = "io.github.joemama.loader.api.BootstrapTransformation"
target = "net.minecraft.server.Bootstrap"

[[mixins]]
path = "api.mixins.json"
