name="Testmod"
version = "1.0-ALPHA"
description = "An API for the ModLoader project"
modid = "loader_api"

[[transforms]]
name = "bootstrap transformation for common entrypoint"
class = "io.github.joemama.loader.api.BootstrapTransformation"
target = "net.minecraft.server.Bootstrap"

[[transforms]]
name = "minecraft transformation for client entrypoint"
class = "io.github.joemama.loader.api.client.MinecraftTransformation"
target = "net.minecraft.client.Minecraft"

[[transforms]]
name = "Main transformation for server entrypoint"
class = "io.github.joemama.loader.api.server.MainTransformation"
target = "net.minecraft.server.Main"

[[mixins]]
path = "api.mixins.json"
